### ISSUE TITLE
pkg_publisher does not appear to work in S12 (build 128)

### ISSUE THREAD

**Issue by wfsaxton** [oracle/puppet-solaris_providers#29]
The simplest example:

```
pkg_publisher { 'solaris':
  origin => 'http://pkg.oracle.com/solaris'
}
```

Produces the following output when the agent is run:

```
Info: Caching catalog for solgen2.us.oracle.com
Info: Applying configuration version 'd261b54492281811e27e7c460eb7ea9d006e76b2'
svcadm: Instance "svc:/application/puppet:agent" is not online.
Error: Failed to apply catalog: undefined method `include?' for nil:NilClass
```

**Comment by shawnferry** [comment]
It would be helpful to have 
puppet module list 
as well as 
puppet apply -vd  --trace whatever.pp or puppet agent --test --trace output to localize the error.

**Comment by shawnferry** [comment]
I am unable to reproduce this issue as described although I am able to reproduce other problems. 

Pull the latest master in a few minutes and see if that works for you.

**Comment by wfsaxton** [comment]
"puppet module list" isn't going to work if I'm running in a master environment running r10k, is it (my apologies, I'm fairly new to Puppet and have only worked in this kind of environment).  Here is out local output on the client:

```
root@solgen2:~# puppet module list
/usr/puppetlabs/puppet/modules
├── oracle-solaris_providers (v2.0.1)
├── puppet-staging (v1.0.7)
├── puppetlabs-concat (v1.2.5)
├── puppetlabs-inifile (v1.6.0)
├── puppetlabs-ntp (v6.1.0)
├── puppetlabs-rsync (v0.4.0)
└── puppetlabs-stdlib (v4.16.0)
```

Here is the output to the other command trace:

```
root@solgen2:~# puppet agent --test --trace --server syscloud-993.us.oracle.com --environment publis
her
svcadm: Instance "svc:/application/puppet:agent" is not in a maintenance or degraded state.
Info: Using configured environment 'publisher'
Info: Retrieving pluginfacts
svcadm: Instance "svc:/application/puppet:agent" is not in a maintenance or degraded state.
Info: Retrieving plugin
svcadm: Instance "svc:/application/puppet:agent" is not in a maintenance or degraded state.
Info: Loading facts
Info: Caching catalog for solgen2.us.oracle.com
Info: Applying configuration version 'a7bca464189a4864876831f2fc794dcf33b8d702'
svcadm: Instance "svc:/application/puppet:agent" is not online.
Error: Failed to apply catalog: undefined method `include?' for nil:NilClass
/var/puppetlabs/puppet/cache/lib/puppet/type/pkg_publisher.rb:172:in `block (3 levels) in <top (required)>'
/var/puppetlabs/puppet/cache/lib/puppet/type/pkg_publisher.rb:170:in `select'
/var/puppetlabs/puppet/cache/lib/puppet/type/pkg_publisher.rb:170:in `block (2 levels) in <top (required)>'
/usr/ruby/2.1/lib/ruby/vendor_ruby/2.1.0/puppet/type.rb:2144:in `instance_eval'
/usr/ruby/2.1/lib/ruby/vendor_ruby/2.1.0/puppet/type.rb:2144:in `block in autorelation'
/usr/ruby/2.1/lib/ruby/vendor_ruby/2.1.0/puppet/type.rb:2083:in `block in eachautorequire'
/usr/ruby/2.1/lib/ruby/vendor_ruby/2.1.0/puppet/type.rb:2082:in `each'
/usr/ruby/2.1/lib/ruby/vendor_ruby/2.1.0/puppet/type.rb:2082:in `eachautorequire'
/usr/ruby/2.1/lib/ruby/vendor_ruby/2.1.0/puppet/type.rb:2139:in `autorelation'
/usr/ruby/2.1/lib/ruby/vendor_ruby/2.1.0/puppet/type.rb:2171:in `autorequire'
/usr/ruby/2.1/lib/ruby/vendor_ruby/2.1.0/puppet/graph/relationship_graph.rb:169:in `block (2 levels) in build_autorelation_dependencies'
/usr/ruby/2.1/lib/ruby/vendor_ruby/2.1.0/puppet/graph/relationship_graph.rb:168:in `each'
/usr/ruby/2.1/lib/ruby/vendor_ruby/2.1.0/puppet/graph/relationship_graph.rb:168:in `block in build_autorelation_dependencies'
/usr/ruby/2.1/lib/ruby/vendor_ruby/2.1.0/puppet/graph/relationship_graph.rb:167:in `each'
/usr/ruby/2.1/lib/ruby/vendor_ruby/2.1.0/puppet/graph/relationship_graph.rb:167:in `build_autorelation_dependencies'
/usr/ruby/2.1/lib/ruby/vendor_ruby/2.1.0/puppet/graph/relationship_graph.rb:25:in `populate_from'
/usr/ruby/2.1/lib/ruby/vendor_ruby/2.1.0/puppet/resource/catalog.rb:246:in `relationship_graph'
/usr/ruby/2.1/lib/ruby/vendor_ruby/2.1.0/puppet/transaction.rb:193:in `relationship_graph'
/usr/ruby/2.1/lib/ruby/vendor_ruby/2.1.0/puppet/transaction.rb:153:in `evaluate'
/usr/ruby/2.1/lib/ruby/vendor_ruby/2.1.0/puppet/resource/catalog.rb:222:in `block in apply'
/usr/ruby/2.1/lib/ruby/vendor_ruby/2.1.0/puppet/util/log.rb:170:in `with_destination'
/usr/ruby/2.1/lib/ruby/vendor_ruby/2.1.0/puppet/transaction/report.rb:142:in `as_logging_destination'
/usr/ruby/2.1/lib/ruby/vendor_ruby/2.1.0/puppet/resource/catalog.rb:221:in `apply'
/usr/ruby/2.1/lib/ruby/vendor_ruby/2.1.0/puppet/configurer.rb:171:in `block in apply_catalog'
/usr/ruby/2.1/lib/ruby/vendor_ruby/2.1.0/puppet/util.rb:224:in `block in benchmark'
/usr/ruby/2.1/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
/usr/ruby/2.1/lib/ruby/vendor_ruby/2.1.0/puppet/util.rb:223:in `benchmark'
/usr/ruby/2.1/lib/ruby/vendor_ruby/2.1.0/puppet/configurer.rb:170:in `apply_catalog'
/usr/ruby/2.1/lib/ruby/vendor_ruby/2.1.0/puppet/configurer.rb:343:in `run_internal'
/usr/ruby/2.1/lib/ruby/vendor_ruby/2.1.0/puppet/configurer.rb:221:in `block in run'
/usr/ruby/2.1/lib/ruby/vendor_ruby/2.1.0/puppet/context.rb:65:in `override'
/usr/ruby/2.1/lib/ruby/vendor_ruby/2.1.0/puppet.rb:294:in `override'
/usr/ruby/2.1/lib/ruby/vendor_ruby/2.1.0/puppet/configurer.rb:195:in `run'
/usr/ruby/2.1/lib/ruby/vendor_ruby/2.1.0/puppet/agent.rb:56:in `block (4 levels) in run'
/usr/ruby/2.1/lib/ruby/vendor_ruby/2.1.0/puppet/agent/locker.rb:21:in `lock'
/usr/ruby/2.1/lib/ruby/vendor_ruby/2.1.0/puppet/agent.rb:56:in `block (3 levels) in run'
/usr/ruby/2.1/lib/ruby/vendor_ruby/2.1.0/puppet/agent.rb:115:in `with_client'
/usr/ruby/2.1/lib/ruby/vendor_ruby/2.1.0/puppet/agent.rb:53:in `block (2 levels) in run'
/usr/ruby/2.1/lib/ruby/vendor_ruby/2.1.0/puppet/agent.rb:82:in `run_in_fork'
/usr/ruby/2.1/lib/ruby/vendor_ruby/2.1.0/puppet/agent.rb:52:in `block in run'
/usr/ruby/2.1/lib/ruby/vendor_ruby/2.1.0/puppet/application.rb:179:in `call'
/usr/ruby/2.1/lib/ruby/vendor_ruby/2.1.0/puppet/application.rb:179:in `controlled_run'
/usr/ruby/2.1/lib/ruby/vendor_ruby/2.1.0/puppet/agent.rb:50:in `run'
/usr/ruby/2.1/lib/ruby/vendor_ruby/2.1.0/puppet/application/agent.rb:353:in `onetime'
/usr/ruby/2.1/lib/ruby/vendor_ruby/2.1.0/puppet/application/agent.rb:331:in `run_command'
/usr/ruby/2.1/lib/ruby/vendor_ruby/2.1.0/puppet/application.rb:358:in `block in run'
/usr/ruby/2.1/lib/ruby/vendor_ruby/2.1.0/puppet/util.rb:542:in `exit_on_fail'
/usr/ruby/2.1/lib/ruby/vendor_ruby/2.1.0/puppet/application.rb:358:in `run'
/usr/ruby/2.1/lib/ruby/vendor_ruby/2.1.0/puppet/util/command_line.rb:132:in `run'
/usr/ruby/2.1/lib/ruby/vendor_ruby/2.1.0/puppet/util/command_line.rb:72:in `execute'
/usr/sbin/puppet:5:in `<main>'
```
